# chart-repo: stable/chartmuseum
# chart-version: latest
# chart-ingress: true
# chart-pvc: chartmuseum ReadWriteOnce 8Gi

fullnameOverride: chartmuseum

env:
  open:
    DISABLE_API: false

service:
  type: SERVICE_TYPE

ingress:
  enabled: INGRESS_ENABLED
  hosts:
    INGRESS_DOMAIN:
      - /
  annotations:
    kubernetes.io/ingress.class: nginx
    # nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 500m
    ingress.kubernetes.io/proxy-body-size: 500m

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 8Gi
  #:EFS:storageClass: "efs"
  existingClaim: chartmuseum
