# chart-repo: stable/jenkins
# chart-version: latest
# chart-ingress: true
# chart-pvc: jenkins ReadWriteOnce 8Gi

# nameOverride: jenkins

rbac:
  install: true

Master:
  # Image: quay.io/nalbam/jenkins
  # ImageTag: latest
  AdminUser: admin
  AdminPassword: PASSWORD
  resources:
    requests:
      cpu: 1000m
      memory: 2048Mi
    limits:
      cpu: 2000m
      memory: 4096Mi
  JavaOpts: "-Dorg.apache.commons.jelly.tags.fmt.timeZone=Asia/Seoul"
  ServiceType: SERVICE_TYPE
  HostName: INGRESS_DOMAIN
  # Ingress:
  #   ApiVersion: extensions/v1beta1
  #   kubernetes.io/ingress.class: nginx
  #   TLS:
  #   - secretName: INGRESS_DOMAIN
  #     hosts:
  #       - INGRESS_DOMAIN
  InstallPlugins:
    # https://github.com/helm/charts/blob/master/stable/jenkins/values.yaml
    - kubernetes:latest
    - workflow-job:latest
    - workflow-aggregator:latest
    - credentials-binding:latest
    # https://plugins.jenkins.io/blueocean
    - blueocean:latest
    # https://plugins.jenkins.io/kubernetes-credentials-provider
    - kubernetes-credentials-provider:latest
    # https://plugins.jenkins.io/pipeline-github-lib
    - pipeline-github-lib:latest
    # https://plugins.jenkins.io/active-directory
    - active-directory:latest
    # https://plugins.jenkins.io/role-strategy
    - role-strategy:latest
  # -- jenkins-jobs -- start -- see: jenkins/jobs.sh #
  # -- jenkins-jobs -- end -- #

# Agent:
#   Enabled: true
#   Image: quay.io/nalbam/jnlp-slave
#   ImageTag: latest
#   AlwaysPullImage: true

Persistence:
  Enabled: true
  AccessMode: ReadWriteOnce
  Size: 8Gi
  #:EFS:StorageClass: "efs"
  existingClaim: jenkins
