# chart-repo: stable/sonarqube
# chart-version: latest
# chart-ingress: true
# chart-pvc: sonarqube-sonarqube ReadWriteOnce 10Gi
# chart-pvc: sonarqube-postgresql ReadWriteOnce 8Gi

nameOverride: sonarqube

service:
  type: SERVICE_TYPE

ingress:
  enabled: INGRESS_ENABLED
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 500m
    ingress.kubernetes.io/proxy-body-size: 500m
  hosts:
    - INGRESS_DOMAIN

resources:
  requests:
    cpu: 1000m
    memory: 3072Mi
  limits:
    cpu: 2000m
    memory: 5120Mi

readinessProbe:
  initialDelaySeconds: 300
  periodSeconds: 30
  failureThreshold: 6
livenessProbe:
  initialDelaySeconds: 300
  periodSeconds: 30

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 10Gi
  #:EFS:storageClass: "efs"
  existingClaim: sonarqube-sonarqube

postgresql:
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 8Gi
    #:EFS:storageClass: "efs"
    existingClaim: sonarqube-postgresql
