# chart-repo: stable/sonatype-nexus
# chart-version: 1.15.1
# chart-ingress: true
# chart-pvc: sonatype-nexus-data ReadWriteOnce 30Gi

nameOverride: sonatype-nexus

statefulset:
  enabled: true

nexus:
  serviceType: SERVICE_TYPE
  resources:
    requests:
      cpu: 250m
      memory: 4Gi
    limits:
      cpu: 1000m
      memory: 4Gi
  # podAnnotations:
  #   cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
  livenessProbe:
    initialDelaySeconds: 100
    periodSeconds: 30
    failureThreshold: 12
    path: /
  readinessProbe:
    initialDelaySeconds: 100
    periodSeconds: 30
    failureThreshold: 12
    path: /

nexusProxy:
  env:
    nexusHttpHost: INGRESS_DOMAIN
    # nexusDockerHost: docker-INGRESS_DOMAIN

nexusBackup:
  nexusAdminPassword: PASSWORD

ingress:
  enabled: INGRESS_ENABLED
  tls:
    enabled: false
  annotations:
    kubernetes.io/ingress.class: nginx
    # nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 500m
    ingress.kubernetes.io/proxy-body-size: 500m

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  storageSize: 30Gi
  #:EFS:storageClass: "efs"
  existingClaim: sonatype-nexus-data
