# chart-repo: stable/external-dns
# chart-version: 1.6.2

nameOverride: external-dns

# podAnnotations:
#   cluster-autoscaler.kubernetes.io/safe-to-evict: "true"

sources:
  - service
  # - ingress

aws:
  accessKey: AWS_ACCESS_KEY
  secretKey: AWS_SECRET_KEY

rbac:
  create: true
