# chart-repo: stable/nginx-ingress
# chart-version: 1.4.0

nameOverride: nginx-ingress

controller:
  # kind: DaemonSet
  replicaCount: 2
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 11
  # podAnnotations:
  #   cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
  config:
    use-forwarded-headers: "true"
  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: ""
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
      service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "3600"
      # external-dns.alpha.kubernetes.io/hostname: "demo.opsnow.com."
      # external-dns.alpha.kubernetes.io/ttl: 300
    targetPorts:
      http: http
      https: http
  stats:
    enabled: true
  metrics:
    enabled: true
    service:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "10254"
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
