# chart-repo: stable/efs-provisioner
# chart-version: 0.1.5

nameOverride: efs-provisioner

efsProvisioner:
  efsFileSystemId: EFS_ID
  awsRegion: AWS_REGION
  path: /shared
  provisionerName: CLUSTER_NAME/efs
  storageClass:
    name: efs
    isDefault: false
    gidAllocate:
      enabled: true
      gidMin: 40000
      gidMax: 50000
    reclaimPolicy: Retain
