# chart-repo: stable/metrics-server
# chart-version: 2.3.0
# chart-pdb: N 1

nameOverride: metrics-server

args:
  # - --logtostderr
  # enable this if you have self-signed certificates
  - --kubelet-insecure-tls
  - --kubelet-preferred-address-types=InternalIP,InternalDNS,ExternalDNS,ExternalIP,Hostname
  # - --source=kubernetes.summary_api:''
  # - --source=kubernetes.summary_api:https://kubernetes.default.svc?kubeletHttps=true&kubeletPort=10250&useServiceAccount=true&insecure=true
  # https://github.com/kubernetes/kubernetes/issues/67702
  # - --requestheader-client-ca-file=/etc/kubernetes/cert/ca.pem
  # - --enable-aggregator-routing=true
