# chart-repo: incubator/vault
# chart-version: latest
# chart-ingress: true

nameOverride: vault

#:STORAGE:vault:
#:STORAGE:  config:
#:STORAGE:    storage:
#:STORAGE:      s3:
#:STORAGE:        access_key: "AWS_ACCESS_KEY"
#:STORAGE:        secret_key: "AWS_SECRET_KEY"
#:STORAGE:        bucket: "AWS_BUCKET"
#:STORAGE:        region: "AWS_REGION"

service:
  type: SERVICE_TYPE

ingress:
  enabled: INGRESS_ENABLED
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - INGRESS_DOMAIN
