nameOverride: docker-registry

service:
  type: SERVICE_TYPE

ingress:
  enabled: INGRESS_ENABLED
  hosts:
    - INGRESS_DOMAIN
  path: /
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 500m
    ingress.kubernetes.io/proxy-body-size: 500m

persistence:
  enabled: false
