# chart-version: latest

nameOverride: metrics-server

args:
  - --logtostderr
# enable this if you have self-signed certificates
# see: https://github.com/kubernetes-incubator/metrics-server
  - --kubelet-insecure-tls
