controller:
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 9
    targetCPUUtilizationPercentage: 50
    targetMemoryUtilizationPercentage: 50
  service:
    annotations:
      # replace with the correct value of the generated certificate in the AWS console
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: ""
      # the backend instances are HTTP
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
      # Map port 443
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
      # Increase the ELB idle timeout to avoid issues with WebSockets or Server-Sent Events.
      service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: '3600'
    targetPorts:
      http: http
      https: http
