# chart-repo: custom/elasticsearch-snapshot
# chart-version: latest

image:
  repository: opsnowtools/elasticsearch-snapshot
  tag: v0.1.1

schedule: "SCHEDULE"

restart: RESTART

configmap:
  enabled: true
  name: "CONFIGMAP_NAME"
