# chart-repo: custom/sample-node
# chart-version: latest
# chart-ingress: true

fullnameOverride: sample-node-sample

profile: dev

namespace: sample

image:
  repository: nalbam/sample-node
  tag: alpine

pod:
  labels:
    spotinst.io/pods-contingency: "true"
  annotations:
    cluster-autoscaler.kubernetes.io/safe-to-evict: "true"

# pdb:
#   minAvailable: "20%"
#   maxUnavailable: "20%"

service:
  type: SERVICE_TYPE

ingress:
  enabled: INGRESS_ENABLED
  subdomain: sample-node-NAMESPACE
  basedomain: BASE_DOMAIN
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"

configmap:
  enabled: false
secret:
  enabled: false
