# chart-repo: custom/sample-tomcat
# chart-version: latest
# chart-ingress: true

fullnameOverride: sample-tomcat-sample

profile: dev

namespaces: sample

image:
  repository: nalbam/sample-tomcat
  tag: alpine

pod:
  labels:
    spotinst.io/pods-contingency: "true"
  annotations:
    cluster-autoscaler.kubernetes.io/safe-to-evict: "true"

# pdb:
#   minAvailable: "20%"
#   maxUnavailable: "20%"

service:
  type: SERVICE_TYPE

ingress:
  enabled: INGRESS_ENABLED
  hosts:
    - sample-tomcat-sample.BASE_DOMAIN
  subdomain: ""
  basedomain: ""
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"

hpa:
  enabled: true
  min: 5
  max: 30
  cpu: 65

configmap:
  enabled: false
secret:
  enabled: false
