# chart-repo: stable/datadog
# chart-version: 1.26.0

nameOverride: datadog

# Use 6.9.0-jmx to enable jmx fetch collection
image:
  tag: 6.9.0-jmx

datadog:
  clusterName: CLUSTER_NAME
  apiKey: API_KEY
  appKey: APP_KEY
  apmEnabled: true
  # logsEnabled: true
  # logsConfigContainerCollectAll: true
  env:
    - name: DD_TAGS
      value: "cluster_name:CLUSTER_NAME"

daemonset:
  enabled: true
  useHostPort: true

deployment:
  enabled: true

# clusterAgent:
#   enabled: true
#   token: APP_KEY
#   metricsProvider:
#     enabled: true
#   env:
#     - name: DD_TAGS
#       value: "cluster_name:CLUSTER_NAME"

env:
  - name: DD_AGENT_HOST
    valueFrom:
      fieldRef:
        fieldPath: status.hostIP

kubeStateMetrics:
  enabled: KUBE_STATE_METRICS
