# chart-repo: stable/grafana
# chart-version: latest

nameOverride: grafana

adminUser: admin
adminPassword: PASSWORD

service:
  type: SERVICE_TYPE

ingress:
  enabled: INGRESS_ENABLED
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - INGRESS_DOMAIN

persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 5Gi
  #:EFS:storageClassName: "efs"

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-server
      access: proxy
      isDefault: true

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/default

dashboards:
  default:
    kube-mon:
      url: https://raw.githubusercontent.com/opsnow/kops-cui/master/templates/kube-mon.json
    kube-mon-apps:
      url: https://raw.githubusercontent.com/opsnow/kops-cui/master/templates/kube-mon-apps.json
    # prometheus-stats:
    #   gnetId: 2
    #   revision: 2
    #   datasource: Prometheus
    # prometheus-cluster:
    #   gnetId: 315
    #   revision: 3
    #   datasource: Prometheus

#:LDAP:grafana.ini:
#:LDAP:  auth.ldap:
#:LDAP:    enabled: true
#:LDAP:    allow_sign_up: true
#:LDAP:    config_file: /etc/grafana/ldap.toml

#:LDAP:ldap:
#:LDAP:  existingSecret: "GRAFANA_LDAP"
